# NOTE: These settings can be overridden by environment variables as well, in
# particular:
#
#    PGHOST
#    PGPORT
#    PGUSER
#    PGPASS
#    PGDATABASE

Default: &defaults
  user: PROJECTNAME
  password: PROJECTNAME
  host: localhost
  database: PROJECTNAME
  connections: 10

Development:
  <<: *defaults

Testing:
  database: PROJECTNAME_test
  <<: *defaults

Staging:
  database: PROJECTNAME_staging
  connections: 100
  <<: *defaults

Production:
  database: PROJECTNAME_production
  connections: 100
  host: localhost
  <<: *defaults
