# NOTE: These settings can be overridden by environment variables as well, in
# particular:
#
#    MYSQL_HOST
#    MYSQL_PORT
#    MYSQL_USER
#    MYSQL_PASSWORD
#    MYSQL_DATABASE

Default: &defaults
  user: PROJECTNAME
  password: PROJECTNAME
  host: localhost
  port: 3306
  database: PROJECTNAME
  poolsize: 10

Development:
  <<: *defaults

Testing:
  database: PROJECTNAME_test
  <<: *defaults

Staging:
  database: PROJECTNAME_staging
  poolsize: 100
  <<: *defaults

Production:
  database: PROJECTNAME_production
  poolsize: 100
  <<: *defaults
