Default: &defaults
  user: PROJECTNAME
  password: PROJECTNAME
  host: localhost
  port: 3306
  database: PROJECTNAME
  poolsize: 10

Development:
  <<: *defaults

Testing:
  database: PROJECTNAME_test
  <<: *defaults

Staging:
  database: PROJECTNAME_staging
  poolsize: 100
  <<: *defaults

Production:
  database: PROJECTNAME_production
  poolsize: 100
  <<: *defaults
