Default: &defaults
  database: PROJECTNAME.sqlite3
  poolsize: 10

Development:
  <<: *defaults

Testing:
  database: PROJECTNAME_test.sqlite3
  <<: *defaults

Staging:
  database: PROJECTNAME_staging.sqlite3
  poolsize: 100
  <<: *defaults

Production:
  database: PROJECTNAME_production.sqlite3
  poolsize: 100
  <<: *defaults
